" show numbers in margin
set number

" try and determine the type of a file by its name and possibly its contents
filetype indent plugin on

" enable syntax highlighting
syntax on

" better cli completion
set wildmenu

" show partial commands in the last line of the screen
set showcmd

" highlight searches
set hlsearch

" when opening new line and no filetype-specific indenting is enabled, stay at
" the same level of indent
set autoindent

" set update intervals 100ms
set updatetime=100

" ---------- Plugins ----------
call plug#begin('~/.vim/plugged')

Plug 'airblade/vim-gitgutter'
Plug 'mattn/emmet-vim'
Plug 'itchyny/lightline.vim'
Plug 'scrooloose/nerdtree'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
Plug 'lervag/vimtex'
Plug 'vim-syntastic/syntastic'
Plug 'tpope/vim-fugitive'

call plug#end()

" ---------- Status Line ----------
" always display the status line (shows lightline)
set laststatus=2
let g:lightline = {
	\ 'colorscheme': 'jellybeans',
	\ 'active': {
	\ 'left': [ [ 'mode', 'paste' ],
	\	[ 'gitbranch', 'readonly', 'filename', 'modified' ] ]
	\ },
	\ 'component_function': {
	\	'gitbranch': 'fugitive#head'
	\ },
	\ }

" remove the --INSERT-- etc as lightline does that for us now
set noshowmode

" ---------- Vimtex ----------
" prevent, uncommon, .tex extension being mistaken for plaintex
let g:tex_flavor = 'latex'

" ---------- Syntastic ----------
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" ---------- Key Mappings ----------
" map NERDTree to Ctrl-n
map <C-n> :NERDTreeToggle<CR>

" map fzf to ';'
map ; :Files<CR>
