config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_i3:
    src: config/i3
    dst: ~/.config/i3
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_terminator:
    src: config/terminator
    dst: ~/.config/terminator
  f_vimrc:
    src: vimrc
    dst: ~/.vimrc
  f_compton.conf:
    src: config/compton.conf
    dst: ~/.config/compton.conf
  d_rofi:
    src: config/rofi
    dst: ~/.config/rofi
  d_images:
    src: config/images
    dst: ~/.config/images
profiles:
  josh-desktop:
    dotfiles:
    - d_i3
    - d_polybar
    - d_terminator
    - f_vimrc
    - f_compton.conf
    - d_rofi
    - d_images
  josh-laptop:
    dotfiles:
    - d_i3
    - d_polybar
    - d_terminator
    - f_vimrc
    - f_compton.conf
    - d_rofi
    - d_images
